### ISSUE TITLE
如何实现加速？

### ISSUE THREAD

**Issue by Shenghsin** [LeapLabTHU/LAUDNet#1]
作者您好。从库里面的代码来看，对通道、空间维度的动态裁剪都是通过卷积之后apply mask实现，这种方式相对于baseline增加了计算量，在实际的运行中时怎样实现速度提升的呐？？谢谢。

**Comment by yizenghan** [comment]
您好，感谢您的关注！首先这里给的是训练这种网路的实现，在训练中增加的计算量相较于网络来说基本可以忽略不计；
实际运行中，需要修改底层CUDA层面的调度才能取得实际加速，除了手动修改CUDA之外，推荐使用TVM或Cutlass等工具。
